name: Entrypoint Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-entrypoint:
    runs-on: ubuntu-22.04
    container:
      image: silkeh/clang:14
    steps:
    - uses: actions/checkout@v2
    - name: Basic command works
      env:
        INPUT_SOURCES: 'examples/*.c'
        INPUT_EXCLUDES: "examples/file2.c"
        INPUT_STYLE: "LLVM"
      run: |
        ./entrypoint.sh | tee > output
        grep "Checking file: ./examples/file1.c" output | echo "file1.c should be checked"
        grep "Checking file: ./examples/file2.c" output | echo "file 2 should not be checked"; exit 1
        echo "Basic command works"
